"""
ResultReady Report Processing Service

This module coordinates the complete ResultReady workflow.

Responsibilities
----------------
1. Read and extract text from laboratory report PDFs.
2. Generate structured laboratory data using AI.
3. Generate patient-friendly educational analysis.
4. Return data for presentation in the Streamlit UI.

Architecture
------------
PDF Upload
    ↓
pdf_reader.py
    ↓
Text Extraction
    ↓
ai_extractor.py
    ↓
Structured Laboratory Data
    ↓
Educational Analysis
    ↓
Streamlit UI

Design Principles
-----------------
- Education, not diagnosis
- Patient understanding and health literacy
- Appointment readiness
- Responsible AI

Author
------
Madhumitha Sridhar
"""

from pathlib import Path
from typing import BinaryIO

from parser.ai_extractor import LabReportAI
from parser.lab_schema import (
    ExtractedLabReport,
    ReportAnalysis,
)
from parser.pdf_reader import extract_text_from_pdf


class ReportService:
    """
    Coordinates the end-to-end laboratory report workflow.

    This service acts as the primary orchestration layer
    between:

    - PDF text extraction
    - AI-powered laboratory data extraction
    - Patient education generation
    - Streamlit presentation

    The service does not perform any medical interpretation.
    Its purpose is to transform laboratory reports into
    understandable educational content.
    """
    def __init__(self) -> None:
        """
        Initialize the report processing workflow.

        Creates and stores an AI processing engine that is
        reused throughout the application lifecycle.
        """
        self.ai = LabReportAI()

    def process_pdf(
        self,
        pdf_source: str | Path | BinaryIO,
    ):
        """
        Execute the complete laboratory report workflow.

        Parameters
        ----------
        pdf_source : str | Path | BinaryIO
            PDF file path or uploaded file object.

        Returns
        -------
        tuple
            Contains:

            - report_text
            Cleaned text extracted from the PDF.

            - extracted_report
            Structured laboratory data extracted by AI.

            - analysis
            Educational analysis and appointment preparation
            guidance generated by AI.

        Workflow
        --------
        PDF
            ↓
        Text Extraction
            ↓
        Laboratory Result Extraction
            ↓
        Educational Analysis
            ↓
        Streamlit Presentation

        Notes
        -----
        This workflow is designed for patient education
        and does not provide diagnostic recommendations.
        """
        print("\n========== STARTING PDF PROCESSING ==========")

        print("STEP 1: Reading PDF")

        # Extract machine-readable text from the uploaded PDF.
        # Text-based PDFs are currently supported.
        report_text = extract_text_from_pdf(pdf_source)

        # Limit report length to control token usage and
        # maintain predictable inference costs.
        report_text = report_text[:3000]
        print(f"TRUNCATED LENGTH: {len(report_text)}")

        print("STEP 2: PDF Read Complete")
        print(f"Characters extracted: {len(report_text)}")

        print("\nFirst 500 characters:")
        print(report_text[:500])

        print("\nSTEP 3: AI Extraction Starting")

        # Generate structured laboratory data from the
        # extracted report text.
        extracted_report = self.ai.extract_report(
            report_text
        )

        print("STEP 4: AI Extraction Complete")

        print("Extracted Report:")
        print(extracted_report)

        print("\nSTEP 5: Analysis Starting")

        # Generate patient-friendly educational content and
        # healthcare appointment preparation guidance.
        analysis = self.ai.analyze_report(
            extracted_report
        )

        print("STEP 6: Analysis Complete")

        print("========== PDF PROCESSING COMPLETE ==========\n")

        return report_text, extracted_report, analysis

    def answer_question(
        self,
        report: ExtractedLabReport,
        analysis: ReportAnalysis,
        question: str,
    ) -> str:
        """
        Answer a user follow-up question.

        Parameters
        ----------
        report : ExtractedLabReport
            Structured laboratory report content.

        analysis : ReportAnalysis
            Educational analysis generated from the report.

        question : str
            User-entered follow-up question.

        Returns
        -------
        str
            Educational response grounded in the
            report and analysis data.

        Notes
        -----
        This workflow remains subject to the same
        Responsible AI restrictions used throughout
        ResultReady.
        """

        cleaned_question = question.strip()

        if not cleaned_question:
            raise ValueError(
                "Please enter a question."
            )

        print("\n========== QUESTION ==========")
        print(cleaned_question)
        print("==============================\n")

        return self.ai.answer_follow_up(
            report=report,
            analysis=analysis,
            question=cleaned_question,
        )